
{{- if .Values.envoyFilter.create -}}
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: {{ include "istio-basic.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  workloadSelector:
    labels:
      {{- toYaml .Values.selectorLabels | nindent 6 }}
  configPatches:
    # The first patch adds the lua filter to the listener/http connection manager
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.router"
    patch:
      operation: INSERT_BEFORE
      value: # lua filter specification
       name: envoy.lua
       typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
          default_source_code:
            inline_string: |
              function envoy_on_request(request_handle)
                request_handle:headers():add("x-demo-header-request", "my_need_to_do_something")
                request_handle:logWarn("Added x-demo-header-request to request")
              end

              function envoy_on_response(response_handle)
                response_handle:headers():add("x-demo-header-response", "my_need_to_do_something")
                response_handle:logWarn("Added x-demo-header-response to response")
              end
{{- end }}